#
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

include device/motorola/sm7750-common/BoardConfigCommon.mk

DEVICE_PATH := device/motorola/avenger

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := avenger

# Display (1220 x 2712 @ 144Hz)
TARGET_SCREEN_DENSITY := 440

# Kernel & Prebuilts
TARGET_KERNEL_VERSION := 6.6
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img

# Dynamic Partitions
BOARD_SUPER_PARTITION_SIZE := 21474836480

BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4

BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE := 536870912
BOARD_PRODUCTIMAGE_PARTITION_RESERVED_SIZE := 2147483648
BOARD_SYSTEM_EXTIMAGE_PARTITION_RESERVED_SIZE := 536870912
BOARD_VENDORIMAGE_PARTITION_RESERVED_SIZE := 268435456

# Motorola AVB Rollback Index Floor
BOARD_AVB_ROLLBACK_INDEX := 1

# Security patch level
VENDOR_SECURITY_PATCH := 2026-03-01

# SEPolicy
BOARD_VENDOR_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/vendor

# OrangeFox Recovery Project (OFRP) Configuration
OF_SCREEN_H := 2712
OF_STATUS_H := 96
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_CLOCK_POS := 1
OF_USE_GREEN_LED := 0
OF_FLASHLIGHT_ENABLE := 0
OF_MAINTAINER := "Shripad"
FOX_VERSION := "R12.1"
FOX_BUILD_TYPE := "Unofficial"
OF_NO_TREBLE_COMPATIBILITY_CHECK := 1
OF_USE_MAGISKBOOT := 1
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := 1
OF_DONT_KEEP_LOG_HISTORY := 1
FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER := 1

# Inherit proprietary vendor configs
-include vendor/motorola/avenger/BoardConfigVendor.mk
