# GPS Configuration for Motorola Edge 70 Fusion (avenger)
NTP_SERVER=pool.ntp.org
XTRA_SERVER_1=http://xtrapath4.izatcloud.net/xtra3grce.bin
XTRA_SERVER_2=http://xtrapath5.izatcloud.net/xtra3grce.bin
XTRA_SERVER_3=http://xtrapath6.izatcloud.net/xtra3grce.bin
SUPL_HOST=supl.google.com
SUPL_PORT=7275
SUPL_VER=0x20000
SUPL_MODE=1
LPP_PROFILE=3
USE_EMERGENCY_PDN_FOR_EMERGENCY_SUPL=1
A_GLONASS_POS_PROTOCOL_SELECT=0x4
AGPS_CONFIG_INJECT=1
DEFAULT_AGPS_ENABLE=TRUE
ERR_ESTIMATE=0
DEBUG_LEVEL=3
INTERMEDIATE_POS=0
ACCURACY_THRES=0
ENABLE_WIPER=0
CAPABILITIES=0x37
PHONE_TYPE=UMTS
