# Qualcomm Wi-Fi Configuration for Motorola Edge 70 Fusion (avenger)
gChannelBondingMode5GHz=1
gChannelBondingMode24GHz=0
gEnableDFSChnlScan=1
gSetTxPowerLimit=1
gEnableP2pNewOp=1
gEnableModulatedDTIM=1
gMaxLIModulatedDTIM=3
END
